apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: b2b-client-node-modules
  name: b2b-client-node-modules
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
