apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: spa-client-node-modules
  name: spa-client-node-modules
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
