apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssr-client
  labels:
    io.kompose.service: ssr-client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ssr-client
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: ssr-client
    spec:
      containers:
        - name: ssr-client
          image: madamski52081/ssr-client:latest
          command: ["npm", "run", "dev"]
          env:
            - name: NODE_ENV
              value: development
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - mountPath: /app/config
              name: ssr-client-cm0
      restartPolicy: Always
      volumes:
        - name: ssr-client-cm0
          configMap:
            name: ssr-client-cm0
