apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssr-client
  labels:
    io.kompose.service: ssr-client
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: ssr-client
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: ssr-client
    spec:
      containers:
        - name: ssr-client
          image: madamski52081/ssr-client:latest
          workingDir: /app
          command: ["sh", "-c", "npm run start"]
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          env:
            - name: API_URL
              value: "http://backend:3000"
            - name: NEXT_PUBLIC_LOGOUT_URL
              value: "http://backend:3000/auth/logout"
          volumeMounts:
            - mountPath: /app/config
              name: ssr-client-cm0
            - mountPath: /app/.env
              name: ssr-client-env
              subPath: .env
      restartPolicy: Always
      volumes:
        - name: ssr-client-cm0
          configMap:
            name: ssr-client-cm0
        - name: ssr-client-env
          configMap:
            name: ssr-client-cm0
