apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ssr-client-hpa
  namespace: korepetycje
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ssr-client
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
